### ISSUE TITLE
last_revid vs latest_revid

### ISSUE THREAD

**Issue by smctrl** [scp-tcg-jp-j/stjj-aic-server#4]
同じ文脈で使われているように見えるが、どちらが正か調査すること。  
このあたり統一しておかないとあとあと変なバグを入れ込みそうで怖い。

**Comment by kerochan** [comment]
見たところ、APIを用いたリビジョンidの取得時に「lastrevid」という名称が用いられていました。ですので、「last_revid」に統一しようと思いますがどうでしょう。

**Comment by smctrl** [comment]
タイトルがlast_revid vs latest_revidなので少し外れてしまいますが、lastrevidはいかがでしょうか？  
同じくFANDOMを由来とするpageidがpage_idとなっていないのを考慮すると、last_revidよりもlastrevidの方が一貫性があります。

**Comment by smctrl** [comment]
ちなみに、名前を変える場合は対応は以下の2つが必要になります。  
* 現行のlatest_revidを然るべき名前に一斉置換
* 現行のNeDBのlatest_revidを然るべき名前に一斉置換
* STJJ.AICの再起動
これを行ううえでメンテナンス時間として10分ほどのダウンタイムが必要になる見込みです。  
人が少ない時間を狙って再起動したいと考えています（具体的には深夜1時か2時）

**Comment by kerochan** [comment]
lastrevidで統一する案に賛成です。ブランチを切って更新する方が良いでしょうか。

**Comment by kerochan** [comment]
ブランチを切って更新する方が良いでしょうか。

**Comment by smctrl** [comment]
了解しました。それではlastrevidに統一する方向で進めましょう。  
現行のものは既にリリースしたものなので、今時点のmainをpullして、そこから新しくブランチを切って修正という形でお願いできればと思います。ブランチ名はお任せします。

**Comment by kerochan** [comment]
renameブランチにて修正しました

**Comment by smctrl** [comment]
Node側でも #3 対応しました。とりあえずNeDBのバックアップと修正も含めサーバーに反映してみましたが、次のDB変更が上手く行くか見る必要があります。実際の動作がOKならrenameブランチをmainブランチにマージします。

**Comment by smctrl** [comment]
新カード刷ってくれてありがとうございます。10日24時（11日0時）のDB変更が成功しました。データも正しく入っていてlastrevidとして登録されています。  
問題なさそうなのでrenameブランチをmainブランチにマージします。

**Comment by smctrl** [comment]
renameブランチをmainブランチにマージしました。  
特に問題なければrenameブランチとcard-searchブランチを削除しますが、いかがでしょうか？  
別の課題を片付ける際には今回のようにまたmainからブランチを切ります。

**Comment by kerochan** [comment]
返信が遅れてすみません。共に削除しても大丈夫です。

**Comment by smctrl** [comment]
了解しました。renameブランチとcard-searchブランチを削除します。

**Comment by smctrl** [comment]
上記ブランチを削除しました。とりあえずこの問題は解決したと思うのでcloseにします。
